/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.asml;

import java.util.Arrays;
import java.util.List;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

@Configuration
@ComponentScan(basePackages = "com.asml")
public class App implements ApplicationRunner{

    private AppService appService;

    public App(AppService appService){
        this.appService = appService;
    }

    public static void main(String[] args) {
        ApplicationContext context = new AnnotationConfigApplicationContext(App.class);
        context.getBean(ApplicationRunner.class).run(args);
    }

    @Override
    public void run(String... args) {
        appService.testing();
        List<String> datas = Arrays.asList("Data1", "Data2", "Data3");
        datas.stream().forEach(item -> System.out.println(item));
    }


}
interface ApplicationRunner{
    void run(String... args);
}
